name: TheDropper
main: TheDropper\Main
version: 1.0.0
api: 3.0.0
commands:
    td:
        usage: /td <addarena/regsign> <worldname> <amount/[line3]> [line4]
        description: Basic command
        permission: TheDropper.command